### ISSUE TITLE
I know this isn't the right place for this, but it is the only form of contact that I found.

### ISSUE THREAD

**Issue by dewsmith0** [JasonTheKitten/cplat#1]
Hi,
I like ComputerCraft, but I was late for entering the forums before the signup system stopped working. I would need to hack the server and add my own account to it, but that would be duifficult and illegal.
I hope that you answer. 
P.S. Do you know if there's any active admins on the forums?

**Comment by JasonTheKitten** [comment]
No active admins (Lyqyd was demoted so Dan200 was the only one). Luckily, we have these 3 things:
https://forums.computercraft.cc/ (alternate forum)
https://www.reddit.com/r/ComputerCraft/ (CC Reddit)
https://discord.gg/H2UyJXe (CC Discord)
I find it kind of funny that this is the place you found (:
